name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Run unit tests
        run: ./mvnw test

  build-docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-docker-username/tp-cd-java21:main .
          docker push your-docker-username/tp-cd-java21:main

  deploy-render:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Deploy to Render
        env:
          DATABASE_JDBC_URL: ${{ secrets.DATABASE_JDBC_URL }}
        run: |
          curl -X POST https://api.render.com/v1/services/your-service-id/deploys \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache":false}'

  deploy-netlify:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify deploy --dir=netlify-deploy --prod
